[build]
  publish = "public"

# إعادة كتابة داخلية: تبقي /hls/* كما هي، لكن تجلبها من Worker
[[redirects]]
  from = "/hls/*"
  to = "https://hls-proxy.<your-subdomain>.workers.dev/hls/:splat"
  status = 200
  force = true
