name = "races-player"
main = "src/index.js"
compatibility_date = "2025-09-30"

[vars]
# استخدم http لتفادي TLS مع IP؛ غيّرها https لو عندك دومين بشهادة صحيحة
ORIGIN_BASE = "https://blvd-frequently-interventions-covering.trycloudflare.com"
PROXY_TIMEOUT_MS = "15000"
